name: Example Workflow
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@${{ github.event.client_payload.checkout_action_version }}
      - run: echo "Hello, world!"
